language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
      before_install:
        - sudo apt-get install -y python3-dev libasound2-dev
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
install:
  - 'pip install pipenv'
  - 'pipenv sync'
script: 'python -m pytest'